KLEI     1 return {
	override_enabled = true,
	worldgen_preset = "SURVIVAL_TOGETHER",
	settings_preset = "SURVIVAL_TOGETHER",
	overrides = {
		["berrybush"] = "often",
		["carrot"] = "often",
		["carrots_regrowth"] = "fast",
		["evergreen_regrowth"] = "fast",
		["fishschools"] = "always",
		["flint"] = "often",
		["flowers_regrowth"] = "fast",
		["frogs"] = "often",
		["grass"] = "often",
		["ocean_shoal"] = "mostly",
		["rabbits"] = "often",
		["rabbits_setting"] = "often",
		["reeds"] = "often",
		["regrowth"] = "fast",
		["rock_ice"] = "often",
	},
}